add support for illumos/solaris
gofrs/flock pull request #63
Opened 2023-01-22 11:07 UTC by gaige

Solaris/Illumos/SmartOS have basically the same issue as AIX. Consolidated use for both.

2024-06-26 17:21 UTC, ldez commented
Hello,

can you rebase your PR?

FYI, I already added a `go.mod` and the build tags have changed.

2024-06-29 09:15 UTC, gaige commented
@ldez Should be ready to go. Linters, tests, and build all ran on the fork. Let me know if there are other issues. Thank you!

2024-06-29 11:25 UTC, ldez requested changes

2024-06-29 11:25 UTC, ldez commented on flock_fnctl.go
> +//go:build (aix || solaris)
```suggestion
//go:build aix || solaris
```

2024-06-29 11:25 UTC, ldez commented on flock_unix.go
> +//go:build !aix && !windows && !solaris
```suggestion
//go:build !aix && !solaris && !windows
```

2024-06-29 11:25 UTC, ldez commented on flock_fnctl.go
can you rename `flock_fnctl.go` to `flock_unix_variants.go`?

2024-06-29 12:40 UTC, ldez approved these changes
Thank you :+1:

2024-06-29 12:42 UTC, merged